#!/bin/bash
# vim: ai:ts=8:sw=8:noet
set -efCo pipefail
export SHELLOPTS
IFS=$'\t\n'

command -v "git" >/dev/null 2>&1 || {
  echo "please install git"
  exit 1
}
command -v "tfplugindocs" >/dev/null 2>&1 || {
  echo "please install tfplugindocs"
  exit 1
}

./scripts/gen-docs.sh

# Check if we are up to date with autogenerated files.
if [[ -n $(git status --porcelain) ]]; then
  echo 'docs are not up to date!'
  exit 1
else
  echo 'All up to date.'
fi
