name: ci

on: [push, pull_request]

env:
  TF_PLUGIN_DOCS_VERSION: 0.13.0

jobs:
  check-docs:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - uses: actions/checkout@v3
      - name: Check docs up to date
        run: |
          cd /tmp
          curl -L https://github.com/hashicorp/terraform-plugin-docs/releases/download/v${TF_PLUGIN_DOCS_VERSION}/tfplugindocs_${TF_PLUGIN_DOCS_VERSION}_linux_amd64.zip -o f.zip && unzip ./f.zip && chmod a+x tfplugindocs && sudo mv ./tfplugindocs /usr/local/bin/
          cd -

          ./scripts/check-docs-dirty.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    # Execute the checks inside the container instead the VM.
    container: golangci/golangci-lint:v1.44.2-alpine
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/lint.sh

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - uses: actions/checkout@v3
      - run: make test

  acceptance-test:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.0.*'
          - '1.1.*'
          - '1.2.*'
          - 'latest'
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - uses: actions/checkout@v3
      - run: make testacc